
package com.android.gs.global;

/**
 * define interaction MVC
 * 
 * @author: DoanDM
 * @version: 1.0
 * @since: 1.1
 */
public interface ActionEventConstant {
	//action event
	int ACTION_REQUEST_LOGIN = 0;
	int ACTION_LOAD_PRODUCT_LIST = ACTION_REQUEST_LOGIN + 1;
	int ACTION_LOAD_CART_LIST = ACTION_LOAD_PRODUCT_LIST + 1;
	int ACTION_LOAD_BANNER = ACTION_LOAD_CART_LIST + 1;
	int ACTION_LOAD_ALL_CATEGORY = ACTION_LOAD_BANNER + 1;
	int ACTION_REQUEST_PAYMENT = ACTION_LOAD_ALL_CATEGORY + 1;
	//switch activity action
	int ACTION_SWITH_TO_CATEGORY_SCREEN = 0;
	int ACTION_SWITH_TO_LIST_PRODUCT_SCREEN = ACTION_SWITH_TO_CATEGORY_SCREEN + 1;
	int ACTION_SWITH_TO_CART_SCREEN = ACTION_SWITH_TO_LIST_PRODUCT_SCREEN + 1;
	int ACTION_VIEW_PRODUCT_DETAIL = ACTION_SWITH_TO_CART_SCREEN + 1;
	int ACTION_SWITH_TO_VIEW_PAYMENT = ACTION_VIEW_PRODUCT_DETAIL + 1;
}
